#+ summary: Retrieves all the information about brightskyWeatherData Datastreams
#+ description: NOTE! make sure response content type is application/json
#+ endpoint: "http://metaphactory.foodie-cloud.org/sparql?repository=ephedra"
#+ method: GET
#+ limit: 100
#+ offset: 0
#+ defaults:
#+   - inputDate: "2023-08-07"
#+   - inputLat: 52.52
#+   - inputLong: 13.4
#+ endpoint_in_url: False
#+ transform: {
#+   "description": "?info",
#+   "$anchor": "description",
#+   "@iot.count": "?total",
#+   "@iot.nextLink": "?next_link",
#+   "value": {
#+     "@iot.id": "?id",
#+     "@iot.selfLink": "?id_link",
#+     "description": "?desc_info",
#+     "name": "?name",
#+     "observationType": "?obs_type",
#+     "unitOfMeasurement": {
#+       "symbol": "?unit_symbol",
#+       "name": "?unit_name",
#+       "definition": "?unit_definition",
#+     },
#+     "Observations@iot.navigationLink": "?obs_link",
#+     "ObservedProperty@iot.navigationLink": "?op_link",
#+     "Sensor@iot.navigationLink": "?sensor_link",
#+     "Thing@iot.navigationLink": "?thing_link",
#+   }
#+ }
PREFIX dct:<http://purl.org/dc/terms/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX sosa:<http://www.w3.org/ns/sosa/>
PREFIX geo84:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX bsapi:<https://w3id.org/ad4gd/ext/brightsky/>
PREFIX sdm:<https://smartdatamodels.org/>
PREFIX sdmw:<https://smartdatamodels.org/dataModel.Weather/>
SELECT ?info ?total ?obs_type ?unit_definition ?id ?unit_symbol ?unit_name
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Datastreams(",?id,")")) AS ?id_link) 
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Datastreams(",?id,")/Observations")) AS ?obs_link)
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Datastreams(",?id,")/ObservedProperty")) AS ?op_link)
(URI(CONCAT('https://w3id.org/ad4gd/berlin/weather/api/v1.0/Datastreams(',?id,')/Sensor')) AS ?sensor_link)
(URI(CONCAT('https://w3id.org/ad4gd/berlin/weather/api/v1.0/Datastreams(',?id,')/Thing')) AS ?thing_link)
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Datastreams?$top=",xsd:integer(?_limit),"&$skip=", xsd:integer(COALESCE(?_offset, 0))+xsd:integer(?_limit))) AS ?next_link)
WHERE {
	BIND("16"^^xsd:integer as ?total)
	BIND("OGC SensorThings API - Observations" as ?info)
	BIND(URI("http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation") AS ?obs_type)
  BIND(URI("http://qudt.org/2.1/vocab/unit") AS ?unit_definition)
	SERVICE <http://www.metaphacts.com/ontologies/platform/repository/federation#brightskyWeatherData>{
		## inputs
		?results dct:date ?_inputDate;
		geo84:lat ?_inputLat_number;
		geo84:long ?_inputLong_number;
		## outputs
		sdm:source ?source .		
	}	
  {BIND(CONCAT(STR(?source),"-temperature") AS ?id).BIND("°C" as ?unit_symbol).BIND("degree Celsius" as ?unit_name)}
  UNION
  {BIND(CONCAT(STR(?source),"-precipitation") AS ?id).BIND("mm" as ?unit_symbol).BIND("Millimeter" as ?unit_name)}
  UNION
  {BIND(CONCAT(STR(?source),"-atmosphericPressure") AS ?id).BIND("hPa" as ?unit_symbol).BIND("Hectopascal" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-cloudCoverage") AS ?id).BIND("%" as ?unit_symbol).BIND("Percent" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-weatherType") AS ?id).BIND("-" as ?unit_symbol).BIND("Unitless" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-dewPoint") AS ?id).BIND("°C" as ?unit_symbol).BIND("degree Celsius" as ?unit_name)}
  UNION
  {BIND(CONCAT(STR(?source),"-precipitationProbability") AS ?id).BIND("%" as ?unit_symbol).BIND("Percent" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-precipitationProbability6h") AS ?id).BIND("%" as ?unit_symbol).BIND("Percent" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-relativeHumidity") AS ?id).BIND("%" as ?unit_symbol).BIND("Percent" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-directIrradiation") AS ?id).BIND("kWh/m²" as ?unit_symbol).BIND("Kilowatthour per square meter" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-sunshine") AS ?id).BIND("min" as ?unit_symbol).BIND("Minute" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-visibility") AS ?id).BIND("m" as ?unit_symbol).BIND("Meter" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-windDirection") AS ?id).BIND("°" as ?unit_symbol).BIND("Degree" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-windSpeed") AS ?id).BIND("km/h" as ?unit_symbol).BIND("Kilometre per Hour" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-gustDirection") AS ?id).BIND("°" as ?unit_symbol).BIND("Degree" as ?unit_name)}  
  UNION
  {BIND(CONCAT(STR(?source),"-gustSpeed") AS ?id).BIND("km/h" as ?unit_symbol).BIND("Kilometre per Hour" as ?unit_name)}  
}
