#+ summary: "Retrieves all the information about ILIAD Observations"
#+ endpoint: "http://metaphactory.foodie-cloud.org/sparql?repository=ephedra"
#+ method: GET
#+ limit: 100
#+ offset: 0
#+ defaults:
#+   - inputDate: "2023-08-07"
#+   - inputLat: 52.52
#+   - inputLong: 13.4
#+ endpoint_in_url: False
#+ transform: {
#+   "description": "?info",
#+   "$anchor": "description",
#+   "@iot.count": "?total",
#+   "value": {
#+     "@iot.id": "?id",
#+     "@iot.selfLink": "?id_link",
#+     "phenomenonTime": "?resultTime",
#+     "resultTime": "?resultTime",
#+     "result": "?simpleResult",
#+     "Datastream@iot.navigationLink": "?datastream_link",
#+     "FeatureOfInterest@iot.navigationLink": "?feature_link"
#+   }
#+ }
PREFIX dct:<http://purl.org/dc/terms/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX sosa:<http://www.w3.org/ns/sosa/>
PREFIX geo84:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX bsapi:<https://w3id.org/ad4gd/ext/brightsky/>
PREFIX sdmw:<https://smartdatamodels.org/dataModel.Weather/>
SELECT ?info ?total ?id
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Observations(",?id,")")) AS ?id_link) 
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Observations(",?id,")/Datastream")) AS ?datastream_link)
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Observations(",?id,")/FeatureOfInterest")) AS ?feature_link)
(URI(CONCAT("https://w3id.org/ad4gd/berlin/weather/api/v1.0/Observations?$top=",xsd:integer(?_limit),"&$skip=", xsd:integer(COALESCE(?_offset, 0))+xsd:integer(?_limit))) AS ?next_link)
?resultTime ?simpleResult ?observedProperty 
WHERE {
	BIND("400"^^xsd:integer as ?total)
	BIND("OGC SensorThings API - Observations" as ?info)
	SERVICE <http://www.metaphacts.com/ontologies/platform/repository/federation#brightskyWeatherData>{
		## inputs
		?results dct:date ?_inputDate;
		geo84:lat ?_inputLat_number;
		geo84:long ?_inputLong_number;
		## outputs
		sosa:resultTime ?resultTime;
		sdmw:temperature ?temperature;
		sdmw:precipitation ?precipitation;
		sdmw:atmosphericPressure ?atmosphericPressure;
		sdmw:cloudCoverage ?cloudCoverage;
		sdmw:weatherType ?weatherType;
		sdmw:dewPoint ?dewPoint;
		sdmw:precipitationProbability ?precipitationProbability;
		bsapi:precipitationProbability6h ?precipitationProbability6h;
		sdmw:relativeHumidity ?relativeHumidity;
		sdmw:directIrradiation ?directIrradiation;
		bsapi:sunshine ?sunshine;
		sdmw:visibility ?visibility;
		sdmw:windDirection ?windDirection;
		sdmw:windSpeed ?windSpeed;
		bsapi:gustDirection ?gustDirection;
		sdmw:gustSpeed ?gustSpeed.
	}	
  {BIND(CONCAT(MD5(STR(?resultTime)),"-temperature") AS ?id).BIND(?temperature as ?simpleResult).BIND("http://vocab.nerc.ac.uk/standard_name/air_temperature/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-precipitation") AS ?id).BIND(?precipitation as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/precipitation_amount/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-atmosphericPressure") AS ?id).BIND(?atmosphericPressure as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/air_pressure/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-cloudCoverage") AS ?id).BIND(?cloudCoverage as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/cloud_area_fraction/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-weatherType") AS ?id).BIND(?weatherType as ?simpleResult).BIND("https://w3id.org/ad4gd/berlin/weather/property/weatherType/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-dewPoint") AS ?id).BIND(?dewPoint as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/dew_point_temperature/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-precipitationProbability") AS ?id).BIND(?precipitationProbability as ?simpleResult).BIND("https://w3id.org/ad4gd/berlin/weather/property/precipitationProbability/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-precipitationProbability6h") AS ?id).BIND(?precipitationProbability6h as ?simpleResult).BIND("https://w3id.org/ad4gd/berlin/weather/property/precipitationProbability6h/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-relativeHumidity") AS ?id).BIND(?relativeHumidity as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/relative_humidity/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-directIrradiation") AS ?id).BIND(?directIrradiation as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/solar_irradiance/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-sunshine") AS ?id).BIND(?sunshine as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/duration_of_sunshine/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-visibility") AS ?id).BIND(?visibility as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/visibility_in_air/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-windDirection") AS ?id).BIND(?windDirection as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/wind_to_direction/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-windSpeed") AS ?id).BIND(?windSpeed as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/wind_speed_shear/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-gustDirection") AS ?id).BIND(?gustDirection as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/wind_gust_from_direction/" as ?observedProperty)}
  UNION
  {BIND(CONCAT(MD5(STR(?resultTime)),"-gustSpeed") AS ?id).BIND(?gustSpeed as ?simpleResult).BIND("https://vocab.nerc.ac.uk/standard_name/wind_speed_of_gust/" as ?observedProperty)}
}